#!/bin/bash
# TUI Test Framework Template - OpenCLI Testing API
# Generated by Claude Code - Enhanced Version
# Location: /Users/dezmondhollins/opencli/test_tui_template.sh

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   OpenCLI TUI Test Framework - Example Patterns             ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Choose a test pattern to run:"
echo ""
echo "  1) Quick Permission Buffer Test - /help (VISUAL)"
echo "     └─ Tests permission buffer appears and is interactable"
echo ""
echo "  2) Custom Navigation Test - Arrow Keys"
echo "     └─ Tests UP/DOWN navigation with BEFORE/AFTER validation"
echo ""
echo "  3) Headless Test - CI/CD Mode"
echo "     └─ No windows, returns exit codes for automation"
echo ""
echo "  4) Test Multiple Commands"
echo "     └─ Loop through all slash commands"
echo ""
echo "  5) Custom Validation"
echo "     └─ User-defined verify functions"
echo ""
echo "  6) State Collection & Analysis"
echo "     └─ Checkpoint-based testing with detailed analysis"
echo ""
echo "  7) Run ALL patterns sequentially"
echo ""
read -p "Enter choice [1-7]: " choice

case $choice in

    1)
        echo ""
        echo "═══════════════════════════════════════════════════════════════"
        echo "PATTERN 1: Quick Permission Buffer Test - /help Command"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        echo "This test verifies that:"
        echo "  ✓ Permission buffer appears when /help is entered"
        echo "  ✓ Yes/No options are displayed correctly"
        echo "  ✓ Arrow keys (UP/DOWN) navigate between options"
        echo "  ✓ Selection changes are detected (BEFORE/AFTER)"
        echo "  ✓ ENTER key is interactable"
        echo ""
        echo "Visual Mode: LEFT window shows opencli, RIGHT shows test data"
        echo ""
        read -p "Press Enter to start test..."

        python3 << 'PYTHON_EOF'
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.testing import create_permission_buffer_test

# Quick helper function for /help command permission buffer
# This is the simplest way to test permission buffer interactivity

print("\n🚀 Starting /help Permission Buffer Test...\n")
print("LEFT Window: opencli tui will launch")
print("RIGHT Window: Test commands and data collection\n")

# Create pre-configured test for /help command
test = create_permission_buffer_test("/help")

# Run test in visual mode (opens 2 terminal windows)
# visual=True shows everything happening in real-time
result = test.run_test(visual=True)

print("\n" + "="*60)
print("TEST RESULTS - /help Permission Buffer")
print("="*60)

if result.passed:
    print("✅ TEST PASSED")
    print("\n✓ Permission buffer appeared correctly")
    print("✓ Yes/No options displayed")
    print("✓ Navigation worked (UP/DOWN arrows)")
    print("✓ Selection changes detected")
    print("✓ ENTER key interactable")
else:
    print("❌ TEST FAILED")
    print("\nFailing Functions Auto-Detected:")
    for func_info in result.failing_functions:
        print(f"\n📁 File: {func_info['file']}")
        print(f"🎯 Function: {func_info['function']}")
        print(f"📍 Line: {func_info['line']}")
        if func_info.get('suggestion'):
            print(f"💡 Suggestion: {func_info['suggestion']}")

print("\n" + "="*60)
if hasattr(result, 'duration'):
    print(f"Test Duration: {result.duration:.2f}s")
if hasattr(result, 'log_file'):
    print(f"Log file: {result.log_file}")
print("="*60 + "\n")
PYTHON_EOF
        ;;

    2)
        echo ""
        echo "==================================================="
        echo "PATTERN 2: Custom Navigation Test"
        echo "==================================================="
        echo ""
        echo "This pattern builds a custom test sequence from scratch"
        echo "and tests arrow key navigation with state validation."
        echo ""

        python3 << 'PYTHON_EOF'
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.testing import TUITestFramework, TestStep

# Create framework with custom SDK init wait time
# Default is 11 seconds - time to wait for opencli SDK to initialize
framework = TUITestFramework(sdk_init_wait=11)

# Build custom test sequence
print("Building test sequence...")
print("")

# Step 1: Type the command
framework.add_step(
    TestStep.TYPE,
    "/help",
    "Type /help command",
    wait_after=1
)

# Step 2: Autocomplete (first ENTER)
framework.add_step(
    TestStep.ENTER,
    description="Autocomplete command",
    wait_after=1
)

# Step 3: Submit command (second ENTER)
framework.add_step(
    TestStep.ENTER,
    description="Submit command to show permission buffer",
    wait_after=4
)

# Step 4: Collect initial state
framework.add_step(
    TestStep.COLLECT_STATE,
    description="Collect permission buffer state",
    wait_after=2
)

# Step 5: Test DOWN arrow navigation
# AUTO-DETECTION: Framework automatically captures BEFORE and AFTER states
framework.add_step(
    TestStep.DOWN,
    description="Press DOWN arrow to select 'No'",
    wait_after=2
)

# Step 6: Verify selection changed
framework.add_step(
    TestStep.VERIFY_SELECTION,
    description="Verify 'No' is now selected",
    expected_state={"selected": "No"},
    wait_after=1
)

# Step 7: Test UP arrow navigation
framework.add_step(
    TestStep.UP,
    description="Press UP arrow to select 'Yes'",
    wait_after=2
)

# Step 8: Verify selection changed back
framework.add_step(
    TestStep.VERIFY_SELECTION,
    description="Verify 'Yes' is now selected",
    expected_state={"selected": "Yes"},
    wait_after=1
)

# Step 9: Confirm selection
framework.add_step(
    TestStep.ENTER,
    description="Confirm selection",
    wait_after=2
)

print("Running custom test sequence...")
print("Visual mode: Two Terminal windows will open")
print("")

# Run test with visual mode
result = framework.run_test(visual=True)

# Show results
print("")
print("=" * 60)
print("NAVIGATION TEST RESULTS")
print("=" * 60)

if result.passed:
    print("✅ Navigation test PASSED")
    print("   Arrow keys working correctly")
    print("   Selection changes detected")
else:
    print("❌ Navigation test FAILED")
    print(f"   {result.message}")

# Cleanup
framework.cleanup()
PYTHON_EOF
        ;;

    3)
        echo ""
        echo "==================================================="
        echo "PATTERN 3: Headless Test (CI/CD Mode)"
        echo "==================================================="
        echo ""
        echo "This pattern runs tests without visual windows"
        echo "and returns exit codes for CI/CD pipelines."
        echo ""

        python3 << 'PYTHON_EOF'
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.testing import create_permission_buffer_test

# Create test
test = create_permission_buffer_test("/help")

print("Running headless test (no visual windows)...")
print("This mode is suitable for CI/CD pipelines")
print("")

# Run without visual mode
result = test.run_test(visual=False)

print("")
print("=" * 60)
print("HEADLESS TEST RESULTS")
print("=" * 60)

if result.passed:
    print("✅ Test PASSED")
    print("   Permission buffer functional")
    exit_code = 0
else:
    print("❌ Test FAILED")
    print(f"   Message: {result.message}")

    if result.failing_functions:
        print("")
        print("   FAILING FUNCTIONS:")
        for func in result.failing_functions:
            print(f"     → {func.get('function')}()")
            print(f"       File: {func.get('file')}")
            print(f"       Line: {func.get('line')}")

    exit_code = 1

print("")
print(f"Log file: {result.log_file}")
print(f"Exit code: {exit_code}")

# Cleanup
test.cleanup()

# Exit with appropriate code for CI/CD
sys.exit(exit_code)
PYTHON_EOF
        ;;

    4)
        echo ""
        echo "==================================================="
        echo "PATTERN 4: Test Multiple Commands"
        echo "==================================================="
        echo ""
        echo "This pattern tests multiple slash commands and"
        echo "generates a summary report."
        echo ""

        python3 << 'PYTHON_EOF'
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.testing import create_permission_buffer_test

# List of commands to test
commands = ["/help", "/agent", "/model"]

print("Testing multiple commands...")
print(f"Commands to test: {', '.join(commands)}")
print("")

results = {}

for cmd in commands:
    print(f"Testing {cmd}...")
    test = create_permission_buffer_test(command=cmd)
    result = test.run_test(visual=False)
    results[cmd] = result

    status = "✅ PASSED" if result.passed else "❌ FAILED"
    print(f"  {status}")

    test.cleanup()

# Summary report
print("")
print("=" * 60)
print("SUMMARY REPORT")
print("=" * 60)

passed = sum(1 for r in results.values() if r.passed)
total = len(results)

print(f"Total commands tested: {total}")
print(f"Passed: {passed}")
print(f"Failed: {total - passed}")
print("")

for cmd, result in results.items():
    status = "✅" if result.passed else "❌"
    print(f"{status} {cmd}")
    if not result.passed:
        print(f"   → {result.message}")

# Exit with failure if any test failed
exit_code = 0 if all(r.passed for r in results.values()) else 1
sys.exit(exit_code)
PYTHON_EOF
        ;;

    5)
        echo ""
        echo "==================================================="
        echo "PATTERN 5: Custom Validation"
        echo "==================================================="
        echo ""
        echo "This pattern shows how to use custom verify functions"
        echo "for application-specific validation logic."
        echo ""

        python3 << 'PYTHON_EOF'
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.testing import TUITestFramework, TestStep

# Define custom validation function
def verify_permission_buffer_displayed(state):
    """
    Custom verify function that checks if permission buffer is displayed.

    Args:
        state (dict): Current TUI state from COLLECT_STATE

    Returns:
        bool: True if validation passes, False otherwise
    """
    output = state.get('output', '')

    # Check for expected elements
    has_yes_option = 'Yes' in output
    has_no_option = 'No' in output
    has_system_prefix = 'System:' in output

    print(f"  Checking permission buffer elements:")
    print(f"    Has 'Yes' option: {has_yes_option}")
    print(f"    Has 'No' option: {has_no_option}")
    print(f"    Has 'System:' prefix: {has_system_prefix}")

    return has_yes_option and has_no_option and has_system_prefix

# Create framework
framework = TUITestFramework(sdk_init_wait=11)

# Build test with custom validation
framework.add_step(TestStep.TYPE, "/help", "Type command")
framework.add_step(TestStep.ENTER, description="Autocomplete")
framework.add_step(TestStep.ENTER, description="Submit", wait_after=4)

# Use custom verify function
framework.add_step(
    TestStep.COLLECT_STATE,
    description="Verify permission buffer with custom logic",
    verify_fn=verify_permission_buffer_displayed,
    wait_after=2
)

print("Running test with custom validation...")
print("")

result = framework.run_test(visual=True)

print("")
print("=" * 60)
print("CUSTOM VALIDATION RESULTS")
print("=" * 60)

if result.passed:
    print("✅ Custom validation PASSED")
else:
    print("❌ Custom validation FAILED")
    print(f"   {result.message}")

framework.cleanup()
PYTHON_EOF
        ;;

    6)
        echo ""
        echo "==================================================="
        echo "PATTERN 6: State Collection & Analysis"
        echo "==================================================="
        echo ""
        echo "This pattern demonstrates comprehensive state collection"
        echo "at multiple checkpoints for detailed analysis."
        echo ""

        python3 << 'PYTHON_EOF'
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.testing import TUITestFramework, TestStep

framework = TUITestFramework(sdk_init_wait=11)

# Collect state at multiple checkpoints
print("Building test with state collection checkpoints...")
print("")

# Checkpoint 1: Initial state
framework.add_step(
    TestStep.COLLECT_STATE,
    description="CHECKPOINT 1: Initial TUI state",
    wait_after=1
)

# Submit command
framework.add_step(TestStep.TYPE, "/help")
framework.add_step(TestStep.ENTER)
framework.add_step(TestStep.ENTER, wait_after=4)

# Checkpoint 2: Permission buffer displayed
framework.add_step(
    TestStep.COLLECT_STATE,
    description="CHECKPOINT 2: Permission buffer displayed",
    wait_after=2
)

# Navigate down
framework.add_step(TestStep.DOWN, description="Navigate to 'No'", wait_after=2)

# Checkpoint 3: After navigation
framework.add_step(
    TestStep.COLLECT_STATE,
    description="CHECKPOINT 3: After DOWN navigation",
    wait_after=1
)

# Navigate up
framework.add_step(TestStep.UP, description="Navigate to 'Yes'", wait_after=2)

# Checkpoint 4: After second navigation
framework.add_step(
    TestStep.COLLECT_STATE,
    description="CHECKPOINT 4: After UP navigation",
    wait_after=1
)

print("Running test with state collection...")
print("")

result = framework.run_test(visual=True)

print("")
print("=" * 60)
print("STATE COLLECTION ANALYSIS")
print("=" * 60)

if result.passed:
    print("✅ Test PASSED")
    print("")
    print("State was collected at 4 checkpoints:")
    print("  1. Initial TUI state")
    print("  2. Permission buffer displayed")
    print("  3. After DOWN navigation")
    print("  4. After UP navigation")
    print("")
    print("Review log file for detailed state data:")
    print(f"  {result.log_file}")
else:
    print("❌ Test FAILED")
    print(f"   {result.message}")

framework.cleanup()
PYTHON_EOF
        ;;

    7)
        echo ""
        echo "==================================================="
        echo "RUNNING ALL TEST PATTERNS"
        echo "==================================================="
        echo ""
        echo "This will run all 6 patterns sequentially."
        echo "Visual tests will open windows for each pattern."
        echo ""
        read -p "Continue? (y/n): " confirm

        if [ "$confirm" = "y" ]; then
            $0 1
            echo ""
            echo "---"
            echo ""
            $0 2
            echo ""
            echo "---"
            echo ""
            $0 3
            echo ""
            echo "---"
            echo ""
            $0 4
            echo ""
            echo "---"
            echo ""
            $0 5
            echo ""
            echo "---"
            echo ""
            $0 6
        else
            echo "Cancelled."
        fi
        ;;

    *)
        echo "Invalid choice. Please run again and select 1-7."
        exit 1
        ;;
esac

echo ""
echo "==================================================="
echo "TUI TEST FRAMEWORK - API REFERENCE"
echo "==================================================="
echo ""
echo "Available TestStep Types:"
echo "  • TestStep.TYPE        - Type text into TUI"
echo "  • TestStep.ENTER       - Press Enter key"
echo "  • TestStep.DOWN        - Press DOWN arrow (auto BEFORE/AFTER)"
echo "  • TestStep.UP          - Press UP arrow (auto BEFORE/AFTER)"
echo "  • TestStep.ESCAPE      - Press ESC key"
echo "  • TestStep.WAIT        - Wait specified seconds"
echo "  • TestStep.COLLECT_STATE - Capture current TUI state"
echo "  • TestStep.VERIFY_SELECTION - Verify selection matches expected"
echo ""
echo "Auto-Detection Features:"
echo "  ✓ Permission buffer presence"
echo "  ✓ Yes/No options displayed"
echo "  ✓ Navigation working (arrow keys)"
echo "  ✓ Selection changes (BEFORE/AFTER)"
echo "  ✓ Failing functions (exact file + line number)"
echo ""
echo "Visual vs Headless:"
echo "  • Visual (visual=True):   Opens LEFT and RIGHT windows"
echo "  • Headless (visual=False): No windows, returns TestResult"
echo ""
echo "For more examples, see: examples/test_permission_buffer.py"
echo ""
